apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofepapp-deploy2
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dofepapp2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dofepapp2
    spec:
      containers:
      - name: app-cont
        image: ggeorgievv96/dofepapp2:%IMAGE-PLACEHOLDER2%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dofepapp-svc2
  labels:
    app: dofepapp2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31001
    protocol: TCP
  selector:
    app: dofepapp2
